// Generated by scripts/optimize-images.mjs — do not edit by hand.
export const images: Record<string, { width: number; height: number; variants: number[] }> = {
  "/img/about/1-500x500.webp": {
    "width": 500,
    "height": 500,
    "variants": []
  },
  "/img/about/2-500x500.webp": {
    "width": 500,
    "height": 500,
    "variants": []
  },
  "/img/about/3-500x500.webp": {
    "width": 500,
    "height": 500,
    "variants": []
  },
  "/img/about/4-500x500.webp": {
    "width": 500,
    "height": 500,
    "variants": []
  },
  "/img/blooddonation/blooddonation.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/blooddonation/blooddonation2.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/blooddonation/blooddonation3.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/blooddonation/blooddonation4.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/blooddonation/blooddonation5.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/blooddonation/blooddonation6.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/events/aarti.webp": {
    "width": 1004,
    "height": 1004,
    "variants": [
      480
    ]
  },
  "/img/events/activity.webp": {
    "width": 1080,
    "height": 1080,
    "variants": [
      480
    ]
  },
  "/img/events/activity2.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/events/celebrate.webp": {
    "width": 1080,
    "height": 720,
    "variants": [
      480
    ]
  },
  "/img/events/celebrate2.webp": {
    "width": 1080,
    "height": 720,
    "variants": [
      480
    ]
  },
  "/img/events/event.webp": {
    "width": 1080,
    "height": 1080,
    "variants": [
      480
    ]
  },
  "/img/events/event3.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/events/tour.webp": {
    "width": 1080,
    "height": 1350,
    "variants": [
      480
    ]
  },
  "/img/faci/cctv.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/faci/common-area.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/faci/common-area2.webp": {
    "width": 1056,
    "height": 816,
    "variants": [
      480
    ]
  },
  "/img/faci/gym.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/faci/gym2.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/faci/gym3.webp": {
    "width": 1920,
    "height": 1282,
    "variants": [
      480,
      960
    ]
  },
  "/img/faci/library.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/faci/ramp.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/faci/transport.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/garden/garden.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/garden/garden2.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/garden/garden3.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/garden/garden4.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/garden/garden5.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/garden/garden6.webp": {
    "width": 1920,
    "height": 1282,
    "variants": [
      480,
      960
    ]
  },
  "/img/garden/night.webp": {
    "width": 1080,
    "height": 1080,
    "variants": [
      480
    ]
  },
  "/img/garden/view.webp": {
    "width": 1600,
    "height": 900,
    "variants": [
      480,
      960
    ]
  },
  "/img/health/health1.webp": {
    "width": 720,
    "height": 900,
    "variants": [
      480
    ]
  },
  "/img/health/health2.webp": {
    "width": 720,
    "height": 900,
    "variants": [
      480
    ]
  },
  "/img/health/health3.webp": {
    "width": 720,
    "height": 900,
    "variants": [
      480
    ]
  },
  "/img/health/health5.webp": {
    "width": 720,
    "height": 900,
    "variants": [
      480
    ]
  },
  "/img/homepage/community-greeting.webp": {
    "width": 1920,
    "height": 1282,
    "variants": [
      480,
      960
    ]
  },
  "/img/homepage/group-photo.webp": {
    "width": 1920,
    "height": 1282,
    "variants": [
      480,
      960
    ]
  },
  "/img/homepage/hero1.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/homepage/hero2.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/homepage/inauguration.webp": {
    "width": 1920,
    "height": 1282,
    "variants": [
      480,
      960
    ]
  },
  "/img/logo.webp": {
    "width": 450,
    "height": 127,
    "variants": []
  },
  "/img/main-logo.webp": {
    "width": 130,
    "height": 121,
    "variants": []
  },
  "/img/room/ac.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/room/dining-hall.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/room/doublebed.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/room/flat.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/room/suite.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/room/tv.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  },
  "/img/room/twin-room.webp": {
    "width": 1920,
    "height": 1282,
    "variants": [
      480,
      960
    ]
  },
  "/img/room/washroom.webp": {
    "width": 660,
    "height": 500,
    "variants": [
      480
    ]
  }
};
