// Run `npm run images` after adding or replacing photos in public/img, then commit the results.
// - Re-encodes any non-WebP source (including JPEGs saved with a .webp extension) as WebP.
// - Writes smaller -480w/-960w WebP copies for srcset.
// - Regenerates src/lib/images.generated.ts with each photo's dimensions, used by <Img>.
import { readdir, rm, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";
import sharp from "sharp";

const root = "public/img";
const widths = [480, 960];
const isVariant = file => /-\d+w\.webp$/.test(file);

const manifest = {};
const files = (await readdir(root, { recursive: true }))
  .filter(file => /\.(webp|jpe?g|png)$/i.test(file) && !isVariant(file))
  .sort();

for (const file of files) {
  let path = join(root, file);
  const { format } = await sharp(path).metadata();
  if (format !== "webp") {
    const webpPath = path.replace(/\.(webp|jpe?g|png)$/i, ".webp");
    const buffer = await sharp(path).rotate().webp({ quality: 80 }).toBuffer();
    if (webpPath !== path) await rm(path);
    await writeFile(webpPath, buffer);
    console.log(`Converted ${format} → WebP: ${webpPath}${webpPath !== path ? " (update references to the old path)" : ""}`);
    path = webpPath;
  }

  const { width, height } = await sharp(path).metadata();
  const sourceTime = (await stat(path)).mtimeMs;
  const variants = widths.filter(w => width >= w * 1.25);
  for (const w of variants) {
    const out = path.replace(/\.webp$/, `-${w}w.webp`);
    const existing = await stat(out).catch(() => null);
    if (existing && existing.mtimeMs >= sourceTime) continue;
    await sharp(path).resize({ width: w }).webp({ quality: 75 }).toFile(out);
  }
  manifest[`/${path.replace(/\\/g, "/").replace(/^public\//, "")}`] = { width, height, variants };
}

await writeFile("src/lib/images.generated.ts", `// Generated by scripts/optimize-images.mjs — do not edit by hand.
export const images: Record<string, { width: number; height: number; variants: number[] }> = ${JSON.stringify(manifest, null, 2)};
`);
console.log(`Indexed ${Object.keys(manifest).length} images.`);
